### ISSUE TITLE
Unexpected keyword argument 'also_return_rows'

### ISSUE THREAD

**Issue by jessicatmt** [wawawario2/long_term_memory#15]
Hello! I tried running this extension today, but I seem to get this issue each time. 

  File "/workspace/text-generation-webui/extensions/long_term_memory/script.py", line 255, in custom_generate_chat_prompt
    (prompt, prompt_rows) = generate_chat_prompt(
TypeError: generate_chat_prompt() got an unexpected keyword argument 'also_return_rows'

I looked at some other recent issues, but I believe this is a different error. I haven't done the LTM CONFIG config changes yet, if that's helpful. 

Thanks in advance!

**Comment by wawawario2** [comment]
I'm guessing you're running off an older commit of [oobabooga's repository](https://github.com/oobabooga/text-generation-webui) as this keyword argument was added relatively recently. Try pulling main from his repo. You probably also want to pull master of this extension as well since there were other fixes pushed very recently.

**Comment by jessicatmt** [comment]
Ok, I did a fresh install of oobabooga and your extension and I have both running! 

One thing -- I don't see any memories getting loaded, and I noticed the "Current FIXED context block (ONLY includes example convos)" contains everything in my character.json file. I do have the information in W++ so that might be the issue. I'll try one of the other formats and will start a new bug if I see anything odd.

**Comment by wawawario2** [comment]
> I don't see any memories getting loaded, and I noticed the "Current FIXED context block (ONLY includes example convos)" contains everything in my character.json file.
This could be due to a variety of reasons. You have to manually refresh by clicking "Refresh" to see any changes to the context block in the debug UI. Your saved memories also won't be visible until next time you run your LLM but you can force the extension to override this by clicking "Force reload memories". Aside from that you may want to play with the configuration to decrease the "strictness" for when memories get stored or loaded.

**Comment by wawawario2** [comment]
Closing this issue since the original problem was resolved, feel free to open a new one if you encounter any other issues.
