### ISSUE TITLE
Support separate memories for multiple characters

### ISSUE THREAD

**Issue by wawawario2** [wawawario2/long_term_memory#6]
One simple approach is to detect when the bot character name has changed and build/access the respective long term memory database for said name.

**Comment by wawawario2** [comment]
Some key ideas/points:
- Take the names of `char1` and/or `char2`, normalize them (perhaps by stripping spaces, making them lowercase, etc), and use the names jointly as a key for the underlying character-specific database
- User may change characters on the fly, we must handle this.
- Don't load memories of all characters, just load what's being used, even during switches
- Migration script: fairly straightforward, just relocate the memory db to a different directory on the file system. We can ask the user interactively what (char1, char2) pair they want to use for their existing database and move it under said namespace.

**Comment by digiwombat** [comment]
Adding onto this concept, I'd really love to see a new greeting generation when loading a new character with no chat backlog. Pick a random recent memory and greet based off that.

For example: It picks a memory where you discussed a film you were planning on watching, character welcomes you back asks if you watched it yet. They could also comment on how long it's been since you last spoke or something to that effect based on timestamps.

Might be useful to add session counts in the db based on when it was last cleared so the character doesn't go back too far. A quick glance at the Extensions docs makes that seem like the hooks would need to be expanded a bit for the idea to be feasible, though.

**Comment by wawawario2** [comment]
This is now supported, see https://github.com/wawawario2/long_term_memory/pull/33
As for @digiwombat's request, I'll open a new issue for this.
